name: monthly-check-version-job
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - run: echo "123" > ./app/src/main/java/com/example/startandroidpainting145/DrawPolyToPoly2Dots.kt

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          add: '*.kt'

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3


